inherit_gem:
  jetrockets-standard: config/rails.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - '**/*.md'
    - 'node_modules/**/*'
    - 'db/schema.rb'
  DisplayCopNames: true
  TargetRubyVersion: 3.0.1
  TargetRailsVersion: 6.1

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: compact

Style/SingleLineMethods:
  Enabled: false

Layout/LineLength:
  Max: 140

Lint/ConstantDefinitionInBlock:
  Enabled: false
